# Help command module
function Print-Help {
    Write-Host "Enlightenment Lighthouse Runtime (ELR)"
    Write-Host "Usage: elr [command] [options]"
    Write-Host
    Write-Host "Basic Commands:"
    Write-Host "  version           Print version information"
    Write-Host "  help              Print this help message"
    Write-Host "  start             Start the ELR runtime"
    Write-Host "  stop              Stop the ELR runtime"
    Write-Host "  status            Check the runtime status"
    Write-Host "  list              List all containers"
    Write-Host "  stats             Show container resource usage stats"
    Write-Host "  tray              Start ELR tray application"
    Write-Host
    Write-Host "Network Service Commands:"
    Write-Host "  start-all         Start all network services"
    Write-Host "  stop-all          Stop all network services"
    Write-Host "  start-desktop [IP:Port]  Start Desktop API (default: localhost:8081)"
    Write-Host "  stop-desktop      Stop Desktop API"
    Write-Host "  start-public [IP:Port]  Start Public API (default: localhost:8080)"
    Write-Host "  stop-public       Stop Public API"
    Write-Host "  start-model [IP:Port]   Start Model Service (default: localhost:8082)"
    Write-Host "  stop-model        Stop Model Service"
    Write-Host "  start-micro [IP:Port]   Start Micro Model Server (default: localhost:8083)"
    Write-Host "  stop-micro        Stop Micro Model Server"
    Write-Host "  network-status    Check network status"
    Write-Host "  network-list      List available IPs and Ports"
    Write-Host
    Write-Host "Token Commands:"
    Write-Host "  token             Manage ELR container tokens"
    Write-Host
    Write-Host "Container Commands:"
    Write-Host "  create            Create a new container"
    Write-Host "  run               Create and start a new container"
    Write-Host "  start-container   Start a container"
    Write-Host "  stop-container    Stop a container"
    Write-Host "  delete            Delete a container"
    Write-Host "  inspect           Inspect a container"
    Write-Host "  exec              Execute a command in a container"
    Write-Host "  upload            Upload file to container"
    Write-Host "  run-c             Compile and run a C program"
    Write-Host "  run-python        Run a Python script or code"
    Write-Host "  chat              Interactive chat with model"
    Write-Host
    Write-Host "Sandbox Commands:"
    Write-Host "  sandbox list          List all sandboxes"
    Write-Host "  sandbox get <id>      Get sandbox details"
    Write-Host "  sandbox create [container]  Create a new sandbox"
    Write-Host "  sandbox start <id>    Start a sandbox"
    Write-Host "  sandbox stop <id>     Stop a sandbox"
    Write-Host "  sandbox delete <id>   Delete a sandbox"
    Write-Host "  sandbox load-model <sandbox-id> <model-id>  Load model to sandbox"
    Write-Host "  sandbox unload-model <sandbox-id> <model-id>  Unload model from sandbox"
    Write-Host "  sandbox models <id>   List models in sandbox"
    Write-Host "  sandbox stats <id>    Get sandbox statistics"
    Write-Host
    Write-Host "Options:"
    Write-Host "  --name            Container name"
    Write-Host "  --image           Container image"
    Write-Host "  --id              Container ID"
    Write-Host "  --command         Command to execute"
    Write-Host "  --file            File path for upload"
    Write-Host "  --source          Source file for C program or Python script"
    Write-Host "  --output          Output file for compiled C program"
    Write-Host "  --args            Additional compile arguments"
    Write-Host "  --code            Python code to execute directly"
    Write-Host "  --model           Model file path"
    Write-Host "  --target          Target environment (local, container, sandbox)"
    Write-Host "  --action          Token action (create, validate, refresh, list, revoke)"
    Write-Host "  --description     Token description"
    Write-Host
    Write-Host "Examples:"
    Write-Host "  elr run-c --source hello.c"
    Write-Host "  elr run-c --source hello.c --output hello.exe"
    Write-Host "  elr run-c --source hello.c --args '-Wall -O2'"
    Write-Host "  elr exec --command 'echo Hello, ELR!'"
    Write-Host "  elr upload --file 'C:\path\to\file.txt'"
    Write-Host "  elr run-python --source script.py"
    Write-Host "  elr run-python --code 'print("Hello from Python!")'"
    Write-Host "  elr chat                           Start interactive chat with default local model"
    Write-Host "  elr chat --model path/to/model.py  Start chat with custom local model"
    Write-Host "  elr chat --target container --id elr-1234567890  Start chat with container"
    Write-Host "  elr chat --target sandbox          Start chat with sandbox model"
    Write-Host "  elr start-desktop 192.168.1.100:9081"
    Write-Host "  elr network-list"
    Write-Host "  elr token --action create --description 'Admin Token'"
    Write-Host "  elr tray"
}

